<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 4 Logit Models | Legal Education Analysis in R</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 4 Logit Models | Legal Education Analysis in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Logit Models | Legal Education Analysis in R" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Richard G. Gardiner">


<meta name="date" content="2019-05-15">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="ols.html">
<link rel="next" href="ordered-logit-models.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About the Book</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="ols.html"><a href="ols.html"><i class="fa fa-check"></i><b>3</b> OLS</a><ul>
<li class="chapter" data-level="3.1" data-path="ols.html"><a href="ols.html#intuition"><i class="fa fa-check"></i><b>3.1</b> Intuition</a></li>
<li class="chapter" data-level="3.2" data-path="ols.html"><a href="ols.html#running-your-first-regression"><i class="fa fa-check"></i><b>3.2</b> Running your first regression</a></li>
<li class="chapter" data-level="3.3" data-path="ols.html"><a href="ols.html#advancing-to-multiple-regression"><i class="fa fa-check"></i><b>3.3</b> Advancing to Multiple Regression</a></li>
<li class="chapter" data-level="3.4" data-path="ols.html"><a href="ols.html#checking-assumptions"><i class="fa fa-check"></i><b>3.4</b> Checking Assumptions</a><ul>
<li class="chapter" data-level="3.4.1" data-path="ols.html"><a href="ols.html#normality"><i class="fa fa-check"></i><b>3.4.1</b> Normality</a></li>
<li class="chapter" data-level="3.4.2" data-path="ols.html"><a href="ols.html#heteroskedasticity"><i class="fa fa-check"></i><b>3.4.2</b> Heteroskedasticity</a></li>
<li class="chapter" data-level="3.4.3" data-path="ols.html"><a href="ols.html#multicollinearity"><i class="fa fa-check"></i><b>3.4.3</b> Multicollinearity</a></li>
<li class="chapter" data-level="3.4.4" data-path="ols.html"><a href="ols.html#outliers-and-leverage"><i class="fa fa-check"></i><b>3.4.4</b> Outliers and leverage</a></li>
<li class="chapter" data-level="3.4.5" data-path="ols.html"><a href="ols.html#autocorrelation"><i class="fa fa-check"></i><b>3.4.5</b> Autocorrelation</a></li>
<li class="chapter" data-level="3.4.6" data-path="ols.html"><a href="ols.html#residual-analysis"><i class="fa fa-check"></i><b>3.4.6</b> Residual Analysis</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="ols.html"><a href="ols.html#displaying-results"><i class="fa fa-check"></i><b>3.5</b> Displaying Results</a><ul>
<li class="chapter" data-level="3.5.1" data-path="ols.html"><a href="ols.html#tables"><i class="fa fa-check"></i><b>3.5.1</b> Tables</a></li>
<li class="chapter" data-level="3.5.2" data-path="ols.html"><a href="ols.html#coefplots"><i class="fa fa-check"></i><b>3.5.2</b> Coefplots</a></li>
<li class="chapter" data-level="3.5.3" data-path="ols.html"><a href="ols.html#graphing-predictions"><i class="fa fa-check"></i><b>3.5.3</b> Graphing predictions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="logit-models.html"><a href="logit-models.html"><i class="fa fa-check"></i><b>4</b> Logit Models</a><ul>
<li class="chapter" data-level="4.1" data-path="logit-models.html"><a href="logit-models.html#introducing-logit-models"><i class="fa fa-check"></i><b>4.1</b> Introducing Logit Models</a></li>
<li class="chapter" data-level="4.2" data-path="logit-models.html"><a href="logit-models.html#example-of-logit-model"><i class="fa fa-check"></i><b>4.2</b> Example of Logit Model</a></li>
<li class="chapter" data-level="4.3" data-path="logit-models.html"><a href="logit-models.html#adding-predictions"><i class="fa fa-check"></i><b>4.3</b> Adding Predictions</a></li>
<li class="chapter" data-level="4.4" data-path="logit-models.html"><a href="logit-models.html#how-did-our-model-do"><i class="fa fa-check"></i><b>4.4</b> How did our model do?</a></li>
<li class="chapter" data-level="4.5" data-path="logit-models.html"><a href="logit-models.html#final-words"><i class="fa fa-check"></i><b>4.5</b> Final Words</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ordered-logit-models.html"><a href="ordered-logit-models.html"><i class="fa fa-check"></i><b>5</b> Ordered Logit Models</a><ul>
<li class="chapter" data-level="5.1" data-path="ordered-logit-models.html"><a href="ordered-logit-models.html#data-and-packages"><i class="fa fa-check"></i><b>5.1</b> Data and Packages</a></li>
<li class="chapter" data-level="5.2" data-path="ordered-logit-models.html"><a href="ordered-logit-models.html#running-the-model"><i class="fa fa-check"></i><b>5.2</b> Running the Model</a></li>
<li class="chapter" data-level="5.3" data-path="ordered-logit-models.html"><a href="ordered-logit-models.html#gettin-predictions"><i class="fa fa-check"></i><b>5.3</b> Gettin predictions:</a></li>
<li class="chapter" data-level="5.4" data-path="ordered-logit-models.html"><a href="ordered-logit-models.html#showing-predictions"><i class="fa fa-check"></i><b>5.4</b> Showing predictions</a></li>
<li class="chapter" data-level="5.5" data-path="ordered-logit-models.html"><a href="ordered-logit-models.html#graphing-in-a-tidy-way"><i class="fa fa-check"></i><b>5.5</b> Graphing in a Tidy Way</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multi-level-models.html"><a href="multi-level-models.html"><i class="fa fa-check"></i><b>6</b> Multi Level Models</a><ul>
<li class="chapter" data-level="6.1" data-path="multi-level-models.html"><a href="multi-level-models.html#introduction"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="multi-level-models.html"><a href="multi-level-models.html#full-model"><i class="fa fa-check"></i><b>6.1.1</b> full model</a></li>
<li class="chapter" data-level="6.1.2" data-path="multi-level-models.html"><a href="multi-level-models.html#building-the-model"><i class="fa fa-check"></i><b>6.1.2</b> building the model</a></li>
<li class="chapter" data-level="6.1.3" data-path="multi-level-models.html"><a href="multi-level-models.html#understanding-and-reporting-the-outputs"><i class="fa fa-check"></i><b>6.1.3</b> Understanding and reporting the outputs</a></li>
<li class="chapter" data-level="6.1.4" data-path="multi-level-models.html"><a href="multi-level-models.html#communicating-results"><i class="fa fa-check"></i><b>6.1.4</b> Communicating results</a></li>
<li class="chapter" data-level="6.1.5" data-path="multi-level-models.html"><a href="multi-level-models.html#model-comparison-with-anova"><i class="fa fa-check"></i><b>6.1.5</b> Model comparison with Anova</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="multi-level-models.html"><a href="multi-level-models.html#glms"><i class="fa fa-check"></i><b>6.2</b> GLMs</a><ul>
<li class="chapter" data-level="6.2.1" data-path="multi-level-models.html"><a href="multi-level-models.html#binomial-data"><i class="fa fa-check"></i><b>6.2.1</b> Binomial Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="multi-level-models.html"><a href="multi-level-models.html#count-models"><i class="fa fa-check"></i><b>6.2.2</b> Count models</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="multi-level-models.html"><a href="multi-level-models.html#repeated-measures"><i class="fa fa-check"></i><b>6.3</b> Repeated Measures</a><ul>
<li class="chapter" data-level="6.3.1" data-path="multi-level-models.html"><a href="multi-level-models.html#paired-t-test"><i class="fa fa-check"></i><b>6.3.1</b> Paired T-test</a></li>
<li class="chapter" data-level="6.3.2" data-path="multi-level-models.html"><a href="multi-level-models.html#repeated-measures-anova"><i class="fa fa-check"></i><b>6.3.2</b> Repeated Measures ANOVA</a></li>
<li class="chapter" data-level="6.3.3" data-path="multi-level-models.html"><a href="multi-level-models.html#example-ny-hate-crime-data"><i class="fa fa-check"></i><b>6.3.3</b> Example: NY Hate Crime Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="count-data.html"><a href="count-data.html"><i class="fa fa-check"></i><b>7</b> Count Data</a></li>
<li class="chapter" data-level="8" data-path="lets-fit-the-first-one.html"><a href="lets-fit-the-first-one.html"><i class="fa fa-check"></i><b>8</b> let’s fit the first one:</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Legal Education Analysis in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logit-models" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Logit Models</h1>
<div id="introducing-logit-models" class="section level2">
<h2><span class="header-section-number">4.1</span> Introducing Logit Models</h2>
<p>There are a number of different models that can be run with a binary regression model (BRM) including: Linear Probability Model, Logit Model, Probit Mode, and the Log-Log model. Most commonly we choose between the Logit and Probit model. The logit model in the past has been the default because the error distribution assumptions decreased the computing cost for the probability distribution function. The decision between the logit and probit are essentially arbitrary because the major difference between them (the distribution of the error term) is something we cannot tested.</p>
<p>When specifying a BRM, we make three main assumptions:</p>
<ol style="list-style-type: decimal">
<li>The threshold for 0 is <span class="math inline">\(\tau = 0\)</span></li>
<li>The Conditional mean of <span class="math inline">\(\epsilon\)</span> is 0: <span class="math inline">\(E(\epsilon | X) = 0\)</span></li>
<li>The conditional variance of <span class="math inline">\(\epsilon\)</span> is constant: <span class="math inline">\(Var(\epsilon|X = 1)\)</span> for probit models and <span class="math inline">\(Var(\epsilon|X = \pi/3)\)</span> for logit models.</li>
</ol>
<p>We also assume that there is an unobserved latent variable that we cannot fully observe, but only observe the cut point (pass/fail). We assume that our observed x’s are linearly related to the latent variable <span class="math inline">\(y^*\)</span>.</p>
</div>
<div id="example-of-logit-model" class="section level2">
<h2><span class="header-section-number">4.2</span> Example of Logit Model</h2>
<p>To show an example of a logit model at work, we will examine the titanic dataset. Specifically we will use the titanic package and load the titanic_train dataset. The Dependent Variable is <code>Survived</code> which indicates whether the person survived. Our regressors in this analysis are: Passenger Class (<code>Pclass</code>), Sex (<code>Sex</code>), and Age (<code>Age</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(titanic)</code></pre></div>
<pre><code>## Warning: package &#39;titanic&#39; was built under R version 3.5.3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(modelr)

titanic &lt;-<span class="st"> </span>titanic_train</code></pre></div>
<p>Our model in this case is:</p>
<p><span class="math inline">\(Pr(Surv = 1) = F(\beta_0 + \beta_1Class + \beta_2Sex + \beta_3AGe + \beta_4Cabin)\)</span></p>
<p>Now lets specify the model in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">glm</span>(Survived <span class="op">~</span><span class="st"> </span>Pclass <span class="op">+</span><span class="st"> </span>Sex <span class="op">+</span><span class="st"> </span>Age, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="dt">data =</span> titanic)</code></pre></div>
<p>The code to run the model is very similar to that of an OLS regression. The left hand side of the assignment operator, <code>&lt;-</code>, is the name of the object you are creating. On the right is the actual model you are running. First is the <code>glm</code> which standards for Generalized Linear Models. Just like with OLS regression, the dependent variable is on the left of the tilde <code>~</code>. The right side includes the independent variables. In our case the dependent variable is Survived and the independent variables include: Pclass, Sex, and age. The family option tells the <code>glm()</code> function the type of dependent variable you have. In this case we have a binomial dependent variable. Unless you specify otherwise, the default link function is the a logit model. See this quick <a href="https://www.statmethods.net/advstats/glm.html">page</a> describing the basics of the <code>glm()</code> function. Lastly, we always have to call our dataset.</p>
<p>Now let’s take a look at the model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Pclass + Sex + Age, family = &quot;binomial&quot;, 
##     data = titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7270  -0.6799  -0.3947   0.6483   2.4668  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  5.056006   0.502128  10.069  &lt; 2e-16 ***
## Pclass      -1.288545   0.139259  -9.253  &lt; 2e-16 ***
## Sexmale     -2.522131   0.207283 -12.168  &lt; 2e-16 ***
## Age         -0.036929   0.007628  -4.841 1.29e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 964.52  on 713  degrees of freedom
## Residual deviance: 647.29  on 710  degrees of freedom
##   (177 observations deleted due to missingness)
## AIC: 655.29
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>When it comes to variables, we are looking for directionality and significance (we are given log odds for the coefficient estimate). Remember that the dependent variable is whether the passenger survived. Each of our variables are negative meaning that as they increase, the probability of surviving the titanic crash is lowered. Specifically, as you go up in passenger class and age you are less likely to survive. Men (compared to women) are less likely to survive. All three independent variables are significant at virtually all accepted levels. Lastly, we notice that our AIC is listed at 655.29. This is not informative by itself, but can help when comparing this to other models. In its raw form, coefficient estimates cannot tell us magnitude. Additional steps are necessary to get predictions.</p>
<p>If we did, however, want to get something of substance to report in the talbe, you can take the exponent of the estimate. This will give you the <em>odds ratio</em>. Monogan states that: “the <em>odds</em> of an event is the ratio fo the probability the event occurs to the probabiliity it does not occur <span class="math inline">\(\dfrac{p}{1- p}\)</span>. The odds ratio tells us the multiplicatvie factor by which the odds will change for a unit increase in the predictor.” We can compute it as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(model<span class="op">$</span>coefficients[<span class="op">-</span><span class="dv">1</span>])</code></pre></div>
<pre><code>##     Pclass    Sexmale        Age 
## 0.27567157 0.08028834 0.96374454</code></pre>
<p>In the code above, I excluded the intercept with <code>[-1]</code>. The 0.963 indicates that as you go up in age by 1 year, theodds that you will survive decrease by 0.96, all else equal. If you prefer percentages:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">100</span> <span class="op">*</span><span class="st"> </span>(<span class="kw">exp</span>(model<span class="op">$</span>coefficients[<span class="op">-</span><span class="dv">1</span>])<span class="op">-</span><span class="dv">1</span>)</code></pre></div>
<pre><code>##     Pclass    Sexmale        Age 
## -72.432843 -91.971166  -3.625546</code></pre>
<p>In this case as you increase in age, your odds of surviving decrease by 3.6%.</p>
</div>
<div id="adding-predictions" class="section level2">
<h2><span class="header-section-number">4.3</span> Adding Predictions</h2>
<p>Given that the direct output of a logit model is not particularly helpful. It is nice to create graphs of predicted probabilities. These graphs, generally, create a simulated dataset that is similar to the dataset used to create the model, but will vary one variable while holding the others constant.</p>
<p>The cleanest way that I know of how to make a new dataset is to use the <code>data_grid</code>. The code below calls our original dataset <code>titanic</code>, then calls the <code>data_grid</code> function. Within the data_grid function you call the variable you wish to vary, in our case I picked <code>Age</code>. the <code>.model = model</code> tells data_grid that we want to use all of the predictors in the model we ran, filling them at their typical values (mean or mode). For some reason, the function seems to want to always add in a last <code>NA</code> row at the end so I am filtering it out.</p>
<p>Continuing in the tidy format, we call the <code>add_predictions(model, type = &quot;respone&quot;)</code> which comes from the <code>modelr</code> package. Here we are taking this new dataset we have made with <code>data_grid</code> and adding predictiosn based off of the results of our model. The key difference in this line of code compared to OLS is the additional argument of <code>type = &quot;response&quot;</code> which tells R that we want predicted probabilities.</p>
<p>After creating the predictions, it now becomes a simple graphing problem of figuring out what kind of variable you have for the x-axis and determining the appropriate graph. In this case, the most appropiate would be either a line graph or scatterplot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">data_grid</span>(Age, <span class="dt">.model =</span> model) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Age)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(model, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Age, <span class="dt">y =</span> pred)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="Bookdown_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Now let’s repeat the process for gender:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">titanic <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">data_grid</span>(Sex, <span class="dt">.model =</span> model) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">add_predictions</span>(model, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Sex, <span class="dt">y =</span> pred)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>()</code></pre></div>
<p><img src="Bookdown_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>Basically, don’t be a guy if you want to survive.</p>
<center>
<p><img src="titanic_meme.jpg" /> &lt;&gt;</p>
</div>
<div id="how-did-our-model-do" class="section level2">
<h2><span class="header-section-number">4.4</span> How did our model do?</h2>
<p>One fun way to see how the model performs is to look at a confusion matrix. To create a confusion matrix, have hte model spit out probabilities on the actual data. Then create a new variable that is equal to 1 if the probability is .50 or higher and 0 otherwise. Then you simply have a table that compares the predicted outcome (1,0) to the actual (1,0). The ones that are in the top left and bottom right are the ones that the model correctly predicted, with the other two spots as the mis-classifications.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">confusion &lt;-<span class="st"> </span>titanic 

prediction &lt;-<span class="st"> </span><span class="kw">predict</span>(model, confusion, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)

predicted_classes &lt;-<span class="st"> </span><span class="kw">ifelse</span>(prediction <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)

predicted_classes &lt;-<span class="st"> </span><span class="kw">as.factor</span>(predicted_classes)

<span class="kw">table</span>(titanic<span class="op">$</span>Survived, predicted_classes)</code></pre></div>
<pre><code>##    predicted_classes
##       0   1
##   0 356  68
##   1  83 207</code></pre>
<p>In this case our model correct guessed 356 people not surviving and 207 people as surviving. It incorrectly guessed at 83 would die that actually survived and 68 as surviving who actually died. If we take the correct over total we get the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(<span class="dv">356</span> <span class="op">+</span><span class="st"> </span><span class="dv">207</span>)<span class="op">/</span>(<span class="dv">356</span> <span class="op">+</span><span class="st"> </span><span class="dv">207</span> <span class="op">+</span><span class="st"> </span><span class="dv">83</span> <span class="op">+</span><span class="st"> </span><span class="dv">68</span>)</code></pre></div>
<pre><code>## [1] 0.7885154</code></pre>
<p>So we can correctly predict 78.8%. This is a good improvement than if we just guessed everyone drowned (the model category).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(titanic<span class="op">$</span>Survived)</code></pre></div>
<pre><code>## 
##   0   1 
## 549 342</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">549</span><span class="op">/</span>(<span class="dv">549</span> <span class="op">+</span><span class="st"> </span><span class="dv">342</span>)</code></pre></div>
<pre><code>## [1] 0.6161616</code></pre>
</div>
<div id="final-words" class="section level2">
<h2><span class="header-section-number">4.5</span> Final Words</h2>
<p>This introduction ignored the assumptions that underly logit models. We also ignored probit models. For a better understanding of how these models work, I recommend “Regression Models for Categorical and Limited Dpeendent Variables” by J. Scott Long</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ols.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ordered-logit-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["Bookdown.pdf", "Bookdown.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
